# Generated by Django 5.0.2 on 2025-09-21 22:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'Net Banking'), ('wallet', 'Mobile Wallet')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('transaction_reference', models.CharField(max_length=100, unique=True)),
                ('qr_code_data', models.TextField()),
                ('qr_image_data', models.TextField(blank=True)),
                ('qr_status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('used', 'Used'), ('cancelled', 'Cancelled'), ('replaced', 'Replaced')], default='active', max_length=20)),
                ('expiry_time', models.DateTimeField()),
                ('gateway_payment_id', models.CharField(blank=True, max_length=100)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('scan_count', models.IntegerField(default=0)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_payments_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_payments', to='invoices.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_payments', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'QR Code Payment',
                'verbose_name_plural': 'QR Code Payments',
                'db_table': 'qr_code_payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
