# Generated by Django 5.0.2 on 2025-09-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="business_config",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="business_type",
            field=models.CharField(
                choices=[
                    (
                        "professional",
                        "Professional Services (CA, Consultant, Lawyer, Doctor)",
                    ),
                    ("trader", "Trader (Goods Trading)"),
                    ("manufacturer", "Manufacturer (Production/Manufacturing)"),
                    ("contractor", "Contractor (Service Contractor)"),
                    (
                        "epc_contractor",
                        "EPC Contractor (Engineering, Procurement, Construction)",
                    ),
                    ("manpower_supplier", "Manpower Supplier (HR/Staffing Services)"),
                    ("software_it", "Software/IT Services"),
                    ("transport_logistics", "Transport/Logistics"),
                    ("real_estate", "Real Estate"),
                    ("retail", "Retail Business"),
                    ("hospitality", "Hospitality (Hotels, Restaurants)"),
                    ("healthcare", "Healthcare Services"),
                    ("education", "Education Services"),
                    ("agriculture", "Agriculture/Farming"),
                    ("other", "Other Business Type"),
                ],
                max_length=25,
            ),
        ),
    ]
